### ISSUE TITLE
Using ngx-combo-datepicker in library

### ISSUE THREAD

**Issue by silvl** [katafractari/ngx-combo-datepicker#9]
I am trying to use this in a library and am getting the following error....

node_modules/ngx-combo-datepicker/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

I believe the dependencies in package.json needs to be defined as peerDependencies to resolve this issue.

**Comment by katafractari** [comment]
Something like this?
https://github.com/katafractari/ngx-combo-datepicker/pull/10

**Comment by silvl** [comment]
Yes

**Comment by katafractari** [comment]
@silvl Fixed in 0.0.7. Thanks for your contribution!
